ruby '>=2.3.1'
source 'https://rubygems.org'

# Middleman
gem 'middleman', '~>4.4.2'
gem 'middleman-syntax', '~> 3.2.0'
gem 'middleman-autoprefixer', '~> 2.7.0'
gem 'middleman-livereload'
gem 'middleman-sprockets', '~> 4.1.1'
gem 'rouge', '~> 3.28.0'
gem 'redcarpet', '~> 3.5.1'
gem 'nokogiri', '>= 1.13.4'
gem 'rack', '>= 2.2.3'
gem 'webrick', '>= 1.7.0'
