ruby '>=3.0.0'
source 'https://rubygems.org'

# Middleman
gem 'middleman', '~>4.4.2'
gem 'middleman-syntax', '~> 3.2.0'
gem 'middleman-autoprefixer', '~> 2.7.0'
gem 'middleman-livereload', '~> 3.4.7'
gem 'middleman-sprockets', '~> 4.1.1'
gem 'rouge', '~> 3.28.0'
gem 'redcarpet'
gem 'nokogiri', '~> 1.14.3'
gem 'rack', '~> 2.2.3'
gem 'webrick', '~> 1.7.0'
